version: 2
updates:
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "weekly"
    -   package-ecosystem: "maven"
        directory: "/"
        schedule:
            interval: "weekly"
    -   package-ecosystem: "docker"
        directory: "/"
        schedule:
            interval: "weekly"
    -   package-ecosystem: "npm"
        directory: "/src/main/resources/webgoat/static/js/libs"
        schedule:
            interval: "weekly"